//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainOrder:BaseModel
    {
        
        public Nullable<int> MemberID { get; set; }
        public string OrderNum { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string OrderStatus { get; set; }
        public string ExpressNum { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
